### ISSUE TITLE
Nur ein Kommentar anzeigen

### ISSUE THREAD

**Issue by urbanitesinaframe** [coding-bootcamps-eu/2023-04-final-project-timesnap#34]
In der Video Detailseite werden aktuell noch alle Kommentare angezeigt.

- [ ] Beim Laden der Detailseite soll für die Kommentare nur ein leerer Kommentarcontainer angezeigt werden
- [ ] Info im Container: "Please select a timestamp to show comment"
- [ ] Kommentar sollen erst bei Klick auf den entsprechenden Timestamp eingeblendet werden
- [ ] Klick auf einen weiteren Timestamp ersetzt den aktuellen Kommentar

**Comment by jstephan087** [comment]
Ich würde das hier gerne mit dem add timestamps verbinden. Also vertief dich am besten nicht zu sehr in das Problem. Denn es kann sein, dass ich es umschreiben muss.
