### ISSUE TITLE
Detailseite lassen sich nicht mehr bei Klick auf den Titel aufrufen

### ISSUE THREAD

**Issue by urbanitesinaframe** [coding-bootcamps-eu/2023-04-final-project-timesnap#41]
- Nach Umstellung der Video ID in der db.json lassen sich die Videos nicht mehr per Klick auf den Titel aufrufen
- Videos lassen sich aber noch per http://localhost:8080/videos/uuid direkt ansteuern

**Comment by jstephan087** [comment]
Dieser Fehler ist bei mir nicht vorhanden.
