### ISSUE TITLE
aktion bei klick auf main topic und keytags

### ISSUE THREAD

**Issue by urbanitesinaframe** [coding-bootcamps-eu/2023-04-final-project-timesnap#68]
- [ ] Bei Klick auf das Maintopic soll die suchergebnis seite aufgerufen werden mit weiteren Videos des gleichen Main Topics
- [ ] Bei Klick auf die keytags soll diesuchergebnis seite aufgerufen werden mit weiteren Videos des gleichen keytags

**Comment by jstephan087** [comment]
Wurde in anderem Branch gelöst.
