### ISSUE TITLE
Blocksegment Text & Bild

### ISSUE THREAD

**Issue by jstephan087** [coding-bootcamps-eu/2023-04-final-project-timesnap#7]
Segment besteht aus:

- [x] H2
- [x] Freitext
- [x] Bild
- [x] Button (Issue #6 muss zuvor erledigt sein)

**Comment by urbanitesinaframe** [comment]
- [ ] H2 statt H1

**Comment by jstephan087** [comment]
> * [ ]  H2 statt H1

Hab ich angepasst. Aber lustigerweise kannst du auch meine Einträge editieren.
